### ISSUE TITLE
More flexible folder schema

### ISSUE THREAD

**Issue by PhiLhoSoft** [danielcooper/test-jumper#14]
We have an AngularJS application, with Java back-end, so we use Maven to build the whole application. Therefore, we follow a Maven folder hierarchy...

We have:
- projectName/src/main/webapp/app
- projectName/src/test/js

Then similar layout under the two folders.

Can test-jumper handle such case?

Note also we have names like homeController.js and testHomeController.js
Yes, case changes between the two files (in a previous project, there would have been HomeController and TestHomeController, more regular...).
Is it handled? If not, can it be?

Note: I think the settings should be saved in file local to the current project, eg. like .eslintrc or .jsbeautifyrc. We use some rules in one project, perhaps other rules in other projects, and perhaps we want to contribute to some open source project with different rules...

Same for source file / test templates: they should depend on the language (JS, Ruby, etc.) of the current file!

Good idea! I have a similar plugin in Eclipse, named MoreUnit, if you are curious... I wanted a similar feature in Atom.

**Comment by danielcooper** [comment]
I don't got much of a use for this personally but it sounds like a reasonable addition.

I'd prefer to lean on an outside library to do the per project preferences. 

Something like https://atom.io/packages/editor-settings ?
