### ISSUE TITLE
Settings for different test - file extention

### ISSUE THREAD

**Issue by yanivefraim** [danielcooper/test-jumper#15]
I cannot find those settings (usually I see the settings button when looking at the package inside the ide). Where can I change my tests files extension configurations? (for example, I use:  'filesname.spec.ts')

**Comment by danielcooper** [comment]
I'm not sure what you mean

![image](https://cloud.githubusercontent.com/assets/22127/13284953/9e6ce486-daef-11e5-9ed7-7437ba41166a.png)
