### ISSUE TITLE
path is transformed incorrectly if the filename is repeated earlier in the path

### ISSUE THREAD

**Issue by ajeffrey** [danielcooper/test-jumper#18]
Hi there,

I've set up test-jumper with the following options:

- Source and test locations: `src|test/spec`
- Test-Filename: `%sSpec`

This works great in most cases, but if the filename is present earlier in the file path it can generate an incorrect path for the unit test.

For example, I have a file, `src/framework/connection/connection.ts` whose unit tests reside in `test/spec/framework/connection/connectionSpec.ts`. If I open `connection.ts` and press `cmd+ctrl+.`, the file that opens is `test/spec/framework/connectionSpec/connection.ts`.

I think the logic is replacing the first instance of the matched string, rather than the last.

I'll take a look at creating a pull request for this, if you're happy to merge and publish?

Thanks

**Comment by danielcooper** [comment]
More than happy to accept a pr if you don't mind looking at it.

**Comment by ajeffrey** [comment]
thanks for merging :)
