### ISSUE TITLE
Getting basename of test file is broken if more than a single . appears in file name

### ISSUE THREAD

**Issue by eddiesholl** [danielcooper/test-jumper#20]
I am using a test file naming syntax of `Thing.test.js`, if I am testing `Thing.js`. The regex in `_extensionFreeBasename` is too aggressive, it means if you try to navigate from the test to the subject file, the file is not detected as a test in `filenameIsSpec()`

For example, `_extensionFreeBasename('Thing.test.js)` is `Thing`. Obviously the pattern `%s.test` does not match this.

It's obviously a potentially invasive change, I haven't yet thought through whether it's safe to trim to the last . instead of the first.

**Comment by danielcooper** [comment]
I'm coming from ruby land, so test_spec.rb & test.rb would be the pair.

I don't know of anyone that uses Thing.ex.test but I wouldn't be surprised.

I'm kind of tempted to add options so custom regexes can be added. What do you think?
